"""
CivicMind AI - Insight Agent Schemas

This module contains all Pydantic models used by the Insight Agent.

PURPOSE:
--------
The Insight Agent converts structured outputs from:
- Analytics Agent
- Prediction Agent

into human-readable intelligence using Gemini.

FLOW:
-----
Analytics Results
        +
Prediction Results
        ↓
Insight Agent
        ↓
Gemini
        ↓
Community Insights
"""

from pydantic import BaseModel, Field, ConfigDict


class InsightRequest(BaseModel):
    """
    Request model for generating AI-powered insights.

    Attributes:
        domain:
            Domain being analyzed.
            Examples:
            - environment
            - health
            - mobility

        analytics_summary:
            Summary produced from Analytics Agent.

        prediction_summary:
            Summary produced from Prediction Agent.
    """

    domain: str = Field(
        ...,
        min_length=1,
        description="Community domain being analyzed"
    )

    analytics_summary: str = Field(
        ...,
        min_length=1,
        description="Summary from Analytics Agent"
    )

    prediction_summary: str = Field(
        ...,
        min_length=1,
        description="Summary from Prediction Agent"
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "domain": "environment",
                "analytics_summary":
                    "Dataset contains 1000 rows with quality score 95.",
                "prediction_summary":
                    "AQI expected to increase from 180 to 220."
            }
        }
    )


class InsightResponse(BaseModel):
    """
    Response model containing Gemini-generated insights.

    Attributes:
        domain:
            Domain analyzed.

        insights:
            Human-readable intelligence generated by Gemini.

        model_used:
            Gemini model used for generation.
    """

    domain: str = Field(
        ...,
        description="Analyzed domain"
    )

    insights: str = Field(
        ...,
        description="Generated insights"
    )

    model_used: str = Field(
        ...,
        description="Gemini model used"
    )

    model_config = ConfigDict(
        json_schema_extra={
            "example": {
                "domain": "environment",
                "insights":
                    "Air quality is expected to worsen steadily "
                    "over the next week.",
                "model_used": "gemini-2.5-flash"
            }
        }
    )